#!/usr/bin/env python3
"""
rock_server.py - web control panel for the ROCK 5T stereo recorder.

The Rock-side successor to the Orin's recorder/server.py, in the same visual
language, stripped to what the field needs: two live previews, one record
button, and a Manage Files page. Python stdlib only (no flask).

    sudo python3 rock_server.py     # http://<rock-ip>:8080  (root: mounts USB)
    # or let systemd run it at boot: see rock-recorder.service

No image-quality UI by design: exposure/colour live in the tuned IQ file
(/etc/iqfiles/imx477_RPI-HQ_default.json, generated by iqfiles/gen_imx477_iq.py)
and the sensor mode + bitrate are fixed at the rig's target (4K30, 28 Mbit).
One less thing to get wrong at a game; change the tuning, not the panel.

Design rules (each learned the hard way on this vendor stack):
  - Previews (both cams) run CONTINUOUSLY on the ISP selfpath at 1920x1080/5fps
    and are NEVER stopped or restarted - pipeline churn has locked this board
    up. Their crop selection is reset at start (stale-crop gotcha).
  - Recording runs on the mainpath - a different node, so previews keep running
    during a take. TWO independent files by design: fault isolation, and the
    stitcher pairs full-res frames by timestamp.
  - The record pipeline is the validated one: io-mode=dmabuf + an explicit
    framerate stamp (without it mpph265enc silently ignores bps) + CBR + a
    decoupling queue. Stop = SIGINT to the process group -> gst -e sends EOS ->
    finalized file.
  - Every gst child gets its own process group and is killed on exit; orphans
    otherwise keep the camera nodes open and silently black the next run.
"""

import glob
import http.server
import json
import os
import re
import shutil
import signal
import socket
import socketserver
import subprocess
import threading
import time
import urllib.parse

PORT = 8080
BITRATE = 28_000_000                # per camera; the rig's 4K30 quality target
PREV_JPG = {"0": "/dev/shm/rec_prev0.jpg", "1": "/dev/shm/rec_prev1.jpg"}
CAMS = {
    "0": {"main": "/dev/video22", "self": "/dev/video23"},
    "1": {"main": "/dev/video31", "self": "/dev/video32"},
}

# This panel runs as ROOT (see rock-recorder.service) so it can mount USB
# drives itself - no privileged helper script. Takes therefore go to an
# explicit path, not "~", which would be /root under systemd.
PANEL_USER = "radxa"
REC_DIR = f"/home/{PANEL_USER}/recordings"

_state = {
    "gst": {},                      # continuous preview procs (cam -> Popen)
    "rec": {},                      # cam -> recording Popen
    "rec_name": None,
    "rec_started": None,
    "lock": threading.Lock(),
}
_xfer = {"active": False, "pct": 0, "file": "", "done": False, "error": None, "count": 0}


# ----------------------------------------------------------------- helpers

def sh(cmd, timeout=30):
    return subprocess.run(cmd, shell=True, capture_output=True, text=True, timeout=timeout)


def human(n):
    for unit in ("B", "KB", "MB", "GB", "TB"):
        if n < 1024 or unit == "TB":
            return f"{n:.0f} {unit}" if unit in ("B", "KB") else f"{n:.1f} {unit}"
        n /= 1024.0
    return f"{n:.1f} TB"


def storage_info():
    try:
        st = os.statvfs(REC_DIR if os.path.isdir(REC_DIR) else f"/home/{PANEL_USER}")
    except OSError:
        return None
    total = st.f_blocks * st.f_frsize
    free = st.f_bavail * st.f_frsize
    used = total - free
    hours = free / (2 * BITRATE / 8 * 3600) if BITRATE else 0
    return {"total": human(total), "used": human(used), "free": human(free),
            "free_bytes": free, "pct": int(used / total * 100) if total else 0,
            "hours": round(hours, 1)}


MNT = "/mnt/usb"


def usb_candidates():
    """Unmounted removable partitions we could mount (nothing hardcoded)."""
    out = []
    r = sh("lsblk -J -o PATH,SIZE,FSTYPE,LABEL,MOUNTPOINT,TRAN,HOTPLUG,TYPE")
    try:
        tree = json.loads(r.stdout or "{}").get("blockdevices", [])
    except json.JSONDecodeError:
        return out

    def walk(nodes, removable=False):
        for n in nodes:
            rem = removable or n.get("tran") == "usb" or n.get("hotplug") in (True, "1")
            if (n.get("type") == "part" and rem and not n.get("mountpoint")
                    and n.get("fstype")):
                out.append({"dev": n.get("path"), "size": n.get("size"),
                            "fstype": n.get("fstype"),
                            "label": n.get("label") or os.path.basename(n.get("path", ""))})
            walk(n.get("children") or [], rem)

    walk(tree)
    return out


def mount_usb(dev):
    """Mount a removable partition at /mnt/usb. We run as root, so this is a
    direct call - but still refuse anything that is not a /dev/sdXN partition,
    so a bad request can never be aimed at the NVMe system disk."""
    if not re.fullmatch(r"/dev/sd[a-z][0-9]+", dev or ""):
        return {"ok": False, "msg": f"refusing '{dev}': not a /dev/sdXN partition"}
    if not os.path.exists(dev):
        return {"ok": False, "msg": f"no such device: {dev}"}
    os.makedirs(MNT, exist_ok=True)
    if sh(f"mountpoint -q {MNT}").returncode == 0:
        return {"ok": True, "msg": f"already mounted at {MNT}"}
    fstype = sh(f"lsblk -no FSTYPE {dev}").stdout.strip().splitlines()[:1]
    fstype = fstype[0] if fstype else ""
    # vfat/exfat/ntfs carry no unix ownership: map them to the panel user so
    # the takes are readable over ssh too
    if fstype in ("exfat", "vfat", "ntfs", "ntfs3"):
        uid = sh(f"id -u {PANEL_USER}").stdout.strip()
        gid = sh(f"id -g {PANEL_USER}").stdout.strip()
        opts = f"-o uid={uid},gid={gid},noatime"
    else:
        opts = "-o noatime"
    r = sh(f"mount {opts} {dev} {MNT}", timeout=45)
    if r.returncode != 0:
        return {"ok": False, "msg": (r.stderr or "mount failed").strip()[:300]}
    return {"ok": True, "msg": f"mounted {dev} ({fstype or 'auto'}) -> {MNT}"}


def umount_usb():
    sh("sync", timeout=60)
    r = sh(f"umount {MNT}", timeout=60)
    if r.returncode != 0:
        return {"ok": False, "msg": (r.stderr or "unmount failed - drive in use?").strip()[:300]}
    return {"ok": True, "msg": "unmounted - safe to unplug"}


def usb_targets():
    """Mounted removable drives we could offload to (auto-detected, no config)."""
    out = []
    try:
        with open("/proc/mounts") as f:
            for line in f:
                dev, mnt, fstype = (line.split() + ["", "", ""])[:3]
                mnt = mnt.replace("\\040", " ")
                if not dev.startswith("/dev/"):
                    continue
                if not (mnt.startswith("/media/") or mnt.startswith("/mnt/")):
                    continue
                if fstype in ("squashfs", "tmpfs", "devtmpfs"):
                    continue
                try:
                    st = os.statvfs(mnt)
                    free = st.f_bavail * st.f_frsize
                except OSError:
                    continue
                out.append({"path": mnt, "name": os.path.basename(mnt) or mnt,
                            "free": human(free), "free_bytes": free})
    except OSError:
        pass
    return out


# ----------------------------------------------------------------- previews

def start_previews():
    for cam, c in CAMS.items():
        sh(f"v4l2-ctl -d {c['self']} --set-selection "
           f"target=crop,top=0,left=0,width=3840,height=2160")
        try:
            os.remove(PREV_JPG[cam])
        except FileNotFoundError:
            pass
        pipeline = (f"gst-launch-1.0 v4l2src device={c['self']} ! "
                    f"video/x-raw,format=NV12,width=1920,height=1080 ! videorate ! "
                    f"video/x-raw,framerate=5/1 ! jpegenc quality=80 ! "
                    f"multifilesink location={PREV_JPG[cam]}")
        log = open(f"/tmp/rec_prev{cam}.log", "w")
        # own process group: shell=True means Popen's pid is the shell, so only
        # killpg reaches gst - otherwise previews outlive the server and hold
        # the selfpath nodes, blacking the next run
        _state["gst"][cam] = subprocess.Popen(pipeline, shell=True, stdout=log,
                                              stderr=log, preexec_fn=os.setsid)


def stop_previews():
    for p in _state["gst"].values():
        if p and p.poll() is None:
            try:
                os.killpg(os.getpgid(p.pid), signal.SIGTERM)
            except (ProcessLookupError, PermissionError):
                pass
    _state["gst"] = {}


# ---------------------------------------------------------------- recording

def start_recording():
    if _state["rec"]:
        return {"ok": False, "msg": "already recording"}
    os.makedirs(REC_DIR, exist_ok=True)
    name = time.strftime("take_%Y%m%d_%H%M%S")
    for cam, c in CAMS.items():
        f = os.path.join(REC_DIR, f"{name}_cam{cam}.mkv")
        pipeline = (f"gst-launch-1.0 -e v4l2src device={c['main']} io-mode=dmabuf ! "
                    f"video/x-raw,format=NV12,width=3840,height=2160 ! videorate ! "
                    f"video/x-raw,framerate=30/1 ! "
                    f"queue max-size-buffers=8 max-size-time=0 max-size-bytes=0 ! "
                    f"mpph265enc rc-mode=cbr bps={BITRATE} bps-max={BITRATE * 3 // 2} ! "
                    f"h265parse ! matroskamux ! filesink location={f}")
        log = open(f"/tmp/rec_cam{cam}.log", "w")
        _state["rec"][cam] = subprocess.Popen(pipeline, shell=True, stdout=log,
                                              stderr=log, preexec_fn=os.setsid)
    _state["rec_name"] = name
    _state["rec_started"] = time.time()

    # a pipeline whose device is held dies instantly and leaves a 0-byte file:
    # catch it and say why, rather than listing empty takes
    time.sleep(2)
    dead = []
    for cam, p in _state["rec"].items():
        if p.poll() is not None:
            tail = ""
            try:
                with open(f"/tmp/rec_cam{cam}.log") as fh:
                    lines = [ln for ln in fh.read().splitlines() if ln.strip()]
                tail = " | ".join(lines[-3:])
            except OSError:
                pass
            dead.append(f"cam{cam} pipeline died: {tail[:300]}")
    if dead:
        for cam, p in _state["rec"].items():
            if p.poll() is None:
                os.killpg(os.getpgid(p.pid), signal.SIGINT)
        for f in glob.glob(os.path.join(REC_DIR, f"{name}_cam*.mkv")):
            if os.path.getsize(f) == 0:
                os.remove(f)
        _state["rec"] = {}
        _state["rec_name"] = None
        _state["rec_started"] = None
        return {"ok": False, "msg": "; ".join(dead)}
    return {"ok": True, "msg": f"recording {name}"}


def stop_recording():
    if not _state["rec"]:
        return {"ok": False, "msg": "not recording"}
    for p in _state["rec"].values():
        if p.poll() is None:
            os.killpg(os.getpgid(p.pid), signal.SIGINT)   # gst -e: EOS + finalize
    warn = []
    for cam, p in _state["rec"].items():
        try:
            p.wait(timeout=20)
        except subprocess.TimeoutExpired:
            os.killpg(os.getpgid(p.pid), signal.SIGKILL)
            warn.append(f"cam{cam} force-stopped")
    name = _state["rec_name"]
    _state["rec"] = {}
    _state["rec_name"] = None
    _state["rec_started"] = None
    files = sorted(glob.glob(os.path.join(REC_DIR, f"{name}_cam*.mkv")))
    # created by a root process: give them to the panel user so ssh/scp and
    # manual cleanup do not need sudo
    try:
        uid = int(sh(f"id -u {PANEL_USER}").stdout.strip())
        gid = int(sh(f"id -g {PANEL_USER}").stdout.strip())
        for f in files:
            os.chown(f, uid, gid)
    except (ValueError, OSError):
        pass
    sizes = [f"{os.path.basename(f)} {human(os.path.getsize(f))}" for f in files]
    return {"ok": True, "msg": "saved " + ", ".join(sizes) + ("; " + "; ".join(warn) if warn else "")}


def rec_bytes():
    if not _state["rec_name"]:
        return 0
    return sum(os.path.getsize(f) for f in
               glob.glob(os.path.join(REC_DIR, f"{_state['rec_name']}_cam*.mkv"))
               if os.path.exists(f))


def list_takes():
    out = []
    for f in sorted(glob.glob(os.path.join(REC_DIR, "*.mkv")), reverse=True):
        stt = os.stat(f)
        out.append({"name": os.path.basename(f), "size": human(stt.st_size),
                    "bytes": stt.st_size,
                    "date": time.strftime("%Y-%m-%d %H:%M", time.localtime(stt.st_mtime))})
    return out


# ----------------------------------------------------------------- transfer

def _xfer_worker(names, dest):
    try:
        target = os.path.join(dest, "rock-recordings")
        os.makedirs(target, exist_ok=True)
        srcs = [os.path.join(REC_DIR, n) for n in names
                if os.path.isfile(os.path.join(REC_DIR, n))]
        total = sum(os.path.getsize(s) for s in srcs) or 1
        moved = 0
        for s in srcs:
            _xfer["file"] = os.path.basename(s)
            tmp = os.path.join(target, os.path.basename(s) + ".part")
            with open(s, "rb") as fi, open(tmp, "wb") as fo:
                while True:
                    chunk = fi.read(4 << 20)
                    if not chunk:
                        break
                    fo.write(chunk)
                    moved += len(chunk)
                    _xfer["pct"] = int(moved / total * 100)
            os.replace(tmp, os.path.join(target, os.path.basename(s)))
            if os.path.getsize(os.path.join(target, os.path.basename(s))) != os.path.getsize(s):
                raise OSError(f"size mismatch after copying {os.path.basename(s)}")
            _xfer["count"] += 1
        sh(f"sync")
        _xfer["pct"] = 100
    except Exception as ex:                                  # noqa: BLE001
        _xfer["error"] = repr(ex)
    finally:
        _xfer["active"] = False
        _xfer["done"] = True


def start_transfer(names, dest):
    if _xfer["active"]:
        return {"ok": False, "msg": "a transfer is already running"}
    if _state["rec"]:
        return {"ok": False, "msg": "not while recording"}
    if not names:
        return {"ok": False, "msg": "nothing selected"}
    if not dest or not os.path.isdir(dest):
        return {"ok": False, "msg": "no destination drive"}
    _xfer.update({"active": True, "pct": 0, "file": "", "done": False,
                  "error": None, "count": 0})
    threading.Thread(target=_xfer_worker, args=(names, dest), daemon=True).start()
    return {"ok": True, "msg": f"copying {len(names)} file(s)"}


def delete_takes(names):
    if _state["rec"]:
        return {"ok": False, "msg": "not while recording"}
    n = 0
    for name in names:
        p = os.path.join(REC_DIR, os.path.basename(name))
        if os.path.isfile(p) and p.startswith(os.path.realpath(REC_DIR)):
            os.remove(p)
            n += 1
    return {"ok": True, "msg": f"deleted {n} file(s)"}


# --------------------------------------------------------------------- UI

CSS = """
 :root { color-scheme: dark; }
 body { font-family: system-ui, sans-serif; margin:0; background:#111; color:#eee; }
 .wrap { max-width:760px; margin:0 auto; padding:20px; }
 h1 { font-size:1.2rem; }
 a.back { color:#7fb2d9; text-decoration:none; font-size:.9rem; }
 .card { padding:14px; border-radius:10px; background:#1b1b1b; margin-bottom:16px; }
 .dot { display:inline-block; width:12px; height:12px; border-radius:50%; background:#555;
        margin-right:8px; vertical-align:middle; }
 .dot.rec { background:#e33; animation:pulse 1.2s infinite; }
 @keyframes pulse { 50% { opacity:.3; } }
 button { width:100%; padding:22px; font-size:1.3rem; font-weight:700; border:0;
          border-radius:12px; margin:8px 0; color:#fff; }
 #start { background:#1f8a3b; } #stop { background:#b3271e; }
 button:disabled { opacity:.35; }
 .btnlink { display:block; text-align:center; text-decoration:none; padding:18px;
            font-size:1.15rem; font-weight:700; border-radius:12px; margin:8px 0;
            color:#fff; background:#2a6f9e; }
 .btnlink.disabled { opacity:.35; pointer-events:none; }
 .cams { display:flex; gap:8px; flex-wrap:wrap; }
 .cams figure { flex:1 1 300px; margin:0; }
 .cams img { width:100%; border-radius:8px; background:#000; display:block;
             aspect-ratio:16/9; object-fit:contain; }
 .cams figcaption { font-size:.8rem; color:#888; text-align:center; padding-top:4px; }
 .ok{color:#4caf50}.warn{color:#ffb300}.hot{color:#e33}
 .muted{color:#888; font-size:.85rem; word-break:break-all;}
 table { width:100%; border-collapse:collapse; font-size:.92rem; }
 th,td { padding:6px 8px; border-bottom:1px solid #222; text-align:left; }
 td.sz { text-align:right; font-variant-numeric:tabular-nums; white-space:nowrap; }
 td.dt, th.dt { white-space:nowrap; color:#bbb; font-variant-numeric:tabular-nums; }
 .name { word-break:break-all; }
 .banner { background:#5a1f1f; color:#ffdede; padding:12px; border-radius:10px;
           margin-bottom:16px; }
 .bar { height:14px; background:#333; border-radius:7px; overflow:hidden; }
 .bar > div { height:100%; width:0; background:#1f8a3b; transition:width .3s; }
 .fbtn { width:auto; padding:10px 14px; font-size:1rem; margin:4px 4px 4px 0; }
 .danger { background:#b3271e; } .go { background:#1f8a3b; } .ghost { background:#333; }
 a.dl { color:#7fb2d9; text-decoration:none; }
"""

PAGE = """<!doctype html>
<html lang="en"><head>
<meta charset="utf-8">
<meta name="viewport" content="width=device-width, initial-scale=1">
<title>Stereo Rig</title>
<style>%CSS%</style></head><body><div class="wrap">
 <h1>&#127909; Stereo Rig</h1>
 <div class="card" style="padding:6px">
   <div class="cams">
     <figure><img id="p0" src="/preview0.mjpg" alt="cam0"><figcaption>cam0</figcaption></figure>
     <figure><img id="p1" src="/preview1.mjpg" alt="cam1"><figcaption>cam1</figcaption></figure>
   </div>
 </div>
 <div class="card">
   <span class="dot" id="dot"></span><span id="statetext">&hellip;</span>
   <div id="detail" class="muted"></div>
   <div id="storage" class="muted" style="margin-top:6px"></div>
 </div>
 <button id="start">&#9679; Start Recording</button>
 <button id="stop" disabled>&#9632; Stop Recording</button>
 <a id="manage" href="/files" class="btnlink">&#128193; Manage Files</a>
 <div class="muted" id="msg"></div>
</div>
<script>
const $ = id => document.getElementById(id);
const fmt = s => Math.floor(s/60)+':'+String(s%60).padStart(2,'0');
function storageHtml(st){
  if(!st) return '';
  const gb = st.free_bytes/1e9, cls = gb<20?'hot':gb<80?'warn':'ok';
  return '&#128190; ' + st.used + ' / ' + st.total + ' used ('+st.pct+'%) &middot; '
       + '<span class="'+cls+'">'+st.free+' free</span> &middot; ~'+st.hours+' h of takes';
}
['p0','p1'].forEach(id => { $(id).onerror = () =>
  setTimeout(()=>{ $(id).src = '/preview'+id[1]+'.mjpg?'+Date.now(); }, 1500); });
async function refresh(){
  try{
    const s = await (await fetch('/status')).json();
    $('dot').className = 'dot' + (s.recording?' rec':'');
    $('statetext').textContent = s.recording ? 'RECORDING \\u2014 '+fmt(s.elapsed) : 'Idle';
    $('detail').textContent = s.recording ? s.name+'  \\u00b7  '+s.size : '';
    $('storage').innerHTML = storageHtml(s.storage);
    $('start').disabled = s.recording;
    $('stop').disabled = !s.recording;
    $('manage').classList.toggle('disabled', s.recording);
  }catch(e){ $('statetext').textContent = 'server unreachable'; }
}
$('start').onclick = async () => { $('start').disabled = true;
  const r = await (await fetch('/start')).json();
  $('msg').textContent = r.ok ? '' : r.msg; refresh(); };
$('stop').onclick = async () => { $('stop').disabled = true;
  const r = await (await fetch('/stop')).json();
  $('msg').textContent = r.msg || ''; refresh(); };
setInterval(refresh, 1500); refresh();
</script></body></html>""".replace("%CSS%", CSS)

FILES_PAGE = """<!doctype html>
<html lang="en"><head>
<meta charset="utf-8">
<meta name="viewport" content="width=device-width, initial-scale=1">
<title>Manage Files</title>
<style>%CSS%</style></head><body><div class="wrap">
 <h1>&#128193; Manage Files &nbsp;<a class="back" href="/">&larr; back to recorder</a></h1>
 <div id="recbanner" class="banner" style="display:none">Recording in progress &mdash;
   copy and delete are disabled to protect the take.</div>

 <div class="card">
   <div id="storage" class="muted"></div>
   <div id="usb" class="muted" style="margin-top:8px"></div>
 </div>

 <div class="card" id="xfercard" style="display:none">
   <div>Copying&hellip; <span id="xferpct">0%</span></div>
   <div class="bar"><div id="xferbar"></div></div>
   <div id="xferfile" class="muted" style="margin-top:6px"></div>
 </div>

 <div class="card">
   <button class="fbtn go" id="btnxfer" onclick="xfer()">&#8681; Copy &rarr; USB</button>
   <button class="fbtn danger" onclick="del()">&#128465; Delete selected</button>
   <button class="fbtn ghost" onclick="load()">&#8635; Refresh</button>
   <div class="muted" id="sel" style="margin-top:8px"></div>
 </div>

 <div class="card">
   <table>
     <thead><tr>
       <th><input type="checkbox" id="all" onchange="toggleAll()"></th>
       <th>Take</th><th class="sz">Size</th><th class="dt">Date</th><th></th>
     </tr></thead>
     <tbody id="rows"></tbody>
   </table>
   <div id="note" class="muted" style="margin-top:8px"></div>
 </div>
</div>
<script>
const $ = id => document.getElementById(id);
const esc = s => (''+s).replace(/&/g,'&amp;').replace(/</g,'&lt;').replace(/>/g,'&gt;');
let recording = false, usbPath = '';
function selected(){ return [...document.querySelectorAll('.pick:checked')].map(c=>c.value); }
function toggleAll(){ document.querySelectorAll('.pick').forEach(c=>c.checked=$('all').checked); sel(); }
function sel(){ const n = selected().length; $('sel').textContent = n ? n+' selected' : 'none selected'; }
function storageHtml(st){
  if(!st) return '';
  const gb = st.free_bytes/1e9, cls = gb<20?'hot':gb<80?'warn':'ok';
  return '&#128190; ' + st.used + ' / ' + st.total + ' used &middot; '
       + '<span class="'+cls+'">'+st.free+' free</span> &middot; ~'+st.hours+' h of takes';
}
async function load(){
  const s = await (await fetch('/api/files')).json();
  recording = s.recording; usbPath = s.usb.length ? s.usb[0].path : '';
  $('recbanner').style.display = recording ? 'block' : 'none';
  $('storage').innerHTML = storageHtml(s.storage);
  if(s.usb.length){
    $('usb').innerHTML = '&#128189; USB: <b>'+esc(s.usb[0].name)+'</b> ('+s.usb[0].free
      +' free) &rarr; copies land in <i>rock-recordings/</i> '
      +'<button class="fbtn ghost" onclick="eject()">&#9167; Eject</button>';
  } else if(s.usb_avail.length){
    $('usb').innerHTML = s.usb_avail.map(d =>
      '&#128189; <b>'+esc(d.label)+'</b> '+esc(d.size)+' '+esc(d.fstype)+' ('+esc(d.dev)+') '
      +'<button class="fbtn go" onclick="mount(\\''+esc(d.dev)+'\\')">&#9660; Mount</button>').join('<br>');
  } else {
    $('usb').innerHTML = 'No USB drive detected &mdash; plug one in and hit Refresh.';
  }
  $('btnxfer').disabled = recording || !s.usb.length;
  $('rows').innerHTML = s.takes.map(f =>
    '<tr><td><input type="checkbox" class="pick" value="'+esc(f.name)+'" onchange="sel()"></td>'
    + '<td class="name">'+esc(f.name)+'</td><td class="sz">'+f.size+'</td>'
    + '<td class="dt">'+f.date+'</td>'
    + '<td><a class="dl" href="/dl/'+encodeURIComponent(f.name)+'">download</a></td></tr>').join('')
    || '<tr><td colspan=5 class="muted">no takes yet</td></tr>';
  $('all').checked = false; sel();
  const x = s.xfer;
  $('xfercard').style.display = (x.active || (x.done && x.error)) ? 'block' : 'none';
  $('xferpct').textContent = x.pct + '%';
  $('xferbar').style.width = x.pct + '%';
  $('xferfile').textContent = x.error ? ('ERROR: ' + x.error) : x.file;
  if(x.active) setTimeout(load, 1000);
}
async function mount(dev){
  $('note').textContent = 'mounting '+dev+'\\u2026';
  const r = await (await fetch('/api/mount?dev='+encodeURIComponent(dev))).json();
  $('note').textContent = r.msg || ''; load();
}
async function eject(){
  $('note').textContent = 'flushing and unmounting\\u2026';
  const r = await (await fetch('/api/umount')).json();
  $('note').textContent = r.msg || ''; load();
}
async function xfer(){
  const names = selected(); if(!names.length) return alert('select some takes first');
  const r = await (await fetch('/api/transfer?dest='+encodeURIComponent(usbPath)
      +'&names='+encodeURIComponent(names.join('|')))).json();
  $('note').textContent = r.msg || ''; load();
}
async function del(){
  const names = selected(); if(!names.length) return alert('select some takes first');
  if(!confirm('Delete '+names.length+' file(s)? This cannot be undone.')) return;
  const r = await (await fetch('/api/delete?names='+encodeURIComponent(names.join('|')))).json();
  $('note').textContent = r.msg || ''; load();
}
load();
</script></body></html>""".replace("%CSS%", CSS)


# ----------------------------------------------------------------- server

class Handler(http.server.BaseHTTPRequestHandler):
    def log_message(self, *a):
        pass

    def _send(self, body, ctype="text/html"):
        if isinstance(body, str):
            body = body.encode()
        self.send_response(200)
        self.send_header("Content-Type", ctype)
        self.send_header("Content-Length", str(len(body)))
        self.end_headers()
        self.wfile.write(body)

    def _json(self, obj):
        self._send(json.dumps(obj), "application/json")

    def do_GET(self):
        path, _, qs = self.path.partition("?")
        q = {k: urllib.parse.unquote_plus(v) for k, v in
             (p.split("=", 1) for p in qs.split("&") if "=" in p)}

        if path == "/":
            self._send(PAGE)
        elif path == "/files":
            self._send(FILES_PAGE)
        elif path == "/status":
            self._json({
                "recording": bool(_state["rec"]),
                "elapsed": int(time.time() - _state["rec_started"]) if _state["rec_started"] else 0,
                "name": _state["rec_name"] or "",
                "size": human(rec_bytes()),
                "storage": storage_info(),
            })
        elif path == "/start":
            with _state["lock"]:
                self._json(start_recording())
        elif path == "/stop":
            with _state["lock"]:
                self._json(stop_recording())
        elif path == "/api/files":
            self._json({"takes": list_takes(), "storage": storage_info(),
                        "usb": usb_targets(), "usb_avail": usb_candidates(),
                        "recording": bool(_state["rec"]), "xfer": _xfer})
        elif path == "/api/mount":
            self._json(mount_usb(q.get("dev", "")))
        elif path == "/api/umount":
            self._json(umount_usb())
        elif path == "/api/transfer":
            names = [n for n in q.get("names", "").split("|") if n]
            self._json(start_transfer(names, q.get("dest", "")))
        elif path == "/api/delete":
            names = [n for n in q.get("names", "").split("|") if n]
            with _state["lock"]:
                self._json(delete_takes(names))
        elif path.startswith("/dl/"):
            name = os.path.basename(urllib.parse.unquote(path[4:]))
            f = os.path.join(REC_DIR, name)
            if not os.path.isfile(f):
                self.send_error(404)
                return
            self.send_response(200)
            self.send_header("Content-Type", "video/x-matroska")
            self.send_header("Content-Length", str(os.path.getsize(f)))
            self.send_header("Content-Disposition", f"attachment; filename={name}")
            self.end_headers()
            try:
                with open(f, "rb") as fh:
                    shutil.copyfileobj(fh, self.wfile, 1 << 20)
            except (BrokenPipeError, ConnectionResetError):
                pass
        elif path in ("/preview0.mjpg", "/preview1.mjpg"):
            jpg_path = PREV_JPG[path[8]]
            self.send_response(200)
            self.send_header("Content-Type", "multipart/x-mixed-replace; boundary=frame")
            self.end_headers()
            try:
                while True:
                    try:
                        with open(jpg_path, "rb") as f:
                            jpg = f.read()
                    except FileNotFoundError:
                        jpg = b""
                    if jpg:
                        self.wfile.write(b"--frame\r\nContent-Type: image/jpeg\r\n"
                                         + f"Content-Length: {len(jpg)}\r\n\r\n".encode()
                                         + jpg + b"\r\n")
                    time.sleep(0.25)
            except (BrokenPipeError, ConnectionResetError):
                pass
        else:
            self.send_error(404)


class Server(socketserver.ThreadingMixIn, http.server.HTTPServer):
    daemon_threads = True
    allow_reuse_address = True


def main():
    # only one process can hold a camera node; starting on top of leftovers
    # fails silently (black preview / 0-byte take), so refuse and say who
    held = sh("pgrep -af 'gst-launch.*video(2[23]|3[12])'").stdout.strip()
    if held:
        print("Camera nodes already in use:\n  " + held.replace("\n", "\n  "))
        print("\nClear it with:  sudo pkill -f _server.py; sudo pkill -f gst-launch")
        raise SystemExit(1)

    os.makedirs(REC_DIR, exist_ok=True)
    start_previews()
    ip = "unknown"
    try:
        s = socket.socket(socket.AF_INET, socket.SOCK_DGRAM)
        s.connect(("8.8.8.8", 80))
        ip = s.getsockname()[0]
        s.close()
    except OSError:
        pass
    print(f"Stereo rig panel:  http://{ip}:{PORT}   (takes -> {REC_DIR})")

    srv = Server(("0.0.0.0", PORT), Handler)
    for sig in (signal.SIGTERM, signal.SIGINT):
        signal.signal(sig, lambda *_: srv.shutdown())
    t = threading.Thread(target=srv.serve_forever, daemon=True)
    t.start()
    try:
        t.join()
    finally:
        if _state["rec"]:
            stop_recording()
        stop_previews()


if __name__ == "__main__":
    main()
